#!/bin/bash

cd $OPENSHIFT_REPO_DIR

. ".openshift/vertx-module-registry.config"

cd $OPENSHIFT_DATA_DIR

# Install Vert.x if needed

if [[ -d vert.x-${VERTX_VERSION} ]]; then
	echo "Vert.x ${VERTX_VERSION} already installed."
else
    # Cleanup old versions if Vert.x
	for version in vert.x-*; do 
		echo "Removing $version"
		rm -rf $version 
	done

	echo "Installing Vert.x $VERTX_VERSION"

    if [[ -e ${OPENSHIFT_REPO_DIR}vert.x-${VERTX_VERSION}.tar.gz ]]; then
        echo "Installing Vert.x directly from repository-file"
        tar -xf ${OPENSHIFT_REPO_DIR}vert.x-${VERTX_VERSION}.tar.gz vert.x-${VERTX_VERSION}
    else
        echo "Downloading http://vertx.io/downloads/vert.x-${VERTX_VERSION}.tar.gz"
        curl --insecure -o vert.x-${VERTX_VERSION}.tar.gz "http://vertx.io/downloads/vert.x-${VERTX_VERSION}.tar.gz"
        tar -xf vert.x-${VERTX_VERSION}.tar.gz
        rm vert.x-${VERTX_VERSION}.tar.gz
    fi
fi
